-- ========================================================
-- SCHÉMA DE RÉFÉRENCE — SUPABASE U TRAGULINU
-- Restaurant menu : catégories + produits
-- Les écritures transitent par les route handlers serveur.
-- ========================================================

-- Nettoyage des anciennes tables
DROP TABLE IF EXISTS public.project_submissions CASCADE;
DROP TABLE IF EXISTS public.projects CASCADE;
DROP TABLE IF EXISTS public.adherents CASCADE;
DROP TABLE IF EXISTS public.rose_orders CASCADE;
DROP TABLE IF EXISTS public.events CASCADE;
DROP TABLE IF EXISTS public.menu_items CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;

-- Table des catégories
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table des produits
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT REFERENCES public.categories(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC(10,2) NOT NULL,
  in_stock BOOLEAN DEFAULT true,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index pour la performance
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category_id);
CREATE INDEX IF NOT EXISTS idx_categories_sort ON public.categories(sort_order);

-- Activation du temps réel
ALTER PUBLICATION supabase_realtime ADD TABLE products;
ALTER PUBLICATION supabase_realtime ADD TABLE categories;

-- Row Level Security
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Lecture publique (anon + authenticated)
GRANT SELECT ON public.categories TO anon, authenticated;
GRANT SELECT ON public.products TO anon, authenticated;

CREATE POLICY "Lecture publique des catégories"
  ON public.categories
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "Lecture publique des produits"
  ON public.products
  FOR SELECT
  TO anon, authenticated
  USING (true);

-- Insérer les catégories dans l'ordre vendeur pour U Tragulinu
INSERT INTO categories (name, slug, sort_order) VALUES
  ('À partager / Apéritif', 'a-partager', 10),
  ('Entrées', 'entrees', 20),
  ('Plats', 'plats', 30),
  ('Salades', 'salades', 40),
  ('Desserts', 'desserts', 50),
  ('Glaces', 'glaces', 60),
  ('Cocktails', 'cocktails', 70),
  ('Vins', 'vins', 80),
  ('Bières', 'bieres', 90),
  ('Spiritueux', 'spiritueux', 100),
  ('Softs', 'softs', 110),
  ('Boissons chaudes', 'boissons-chaudes', 120);
